sudo: required
services:
  - docker

before_install:
  - docker build -t phumi/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true phumi/docker-react npm run test

deploy:
  provider: elasticbeantalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket: "elasticbeanstalk-us-east-1-349828761160"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY